apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: roboshop
  labels:
    app: payment
    tier: db
    project: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
      tier: db
      project: roboshop
  template:
    metadata:
      namespace: roboshop
      labels:
        app: payment
        tier: db
        project: roboshop
    spec:
      containers:
      - name: payment
        image: gspvsr/payment:1.0.0
        envFrom: 
        - configMapRef:
            name: payment
---
apiVersion: v1
kind: Service
metadata:
  name: payment
spec:
  selector:
    app: payment
    tier: db
    project: roboshop
  ports:
  - name: mongodb-port
    protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: v1 
kind: ConfigMap
metadata:
  name: payment
  namespace: roboshop
data: 
  CART_HOST: "cart"
  CART_PORT: "8080"
  USER_HOST: "user"
  USER_PORT: "8080"
  AMQP_HOST: "rabbitmq"
  

