apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    app: rabbitmq
    tier: db
    project: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
      tier: db
      project: roboshop
  template:
    metadata:
      namespace: roboshop
      labels:
        app: rabbitmq
        tier: db
        project: roboshop
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
    tier: db
    project: roboshop
  ports:
  - name: rabbitmq
    protocol: TCP
    port: 5672
    targetPort: 5672

      